### ISSUE TITLE
Add support for reporting error without stacktrace

### ISSUE THREAD

**Issue by btomala** [bugsnag/bugsnag-java#144] opened 2019-06-06 13:33 UTC
### Expected behavior
*Report error without stacktrace*

### Observed behavior
*There is no possibility of doing that*

### Steps to reproduce
*Stacktrace is required in Bugsnag client API*

### Version
*3.5.0*

### Additional information
*I understand that your integration is built for Java, but JVM has a lot of languages not all of them are treating exceptions as a default channel of errors. The problem appears when I'm using Scala libraries like Akka which some of the errors logged without a stack trace. I didn't see them in Bugsnag. Is there a chance to fix it?*

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by fractalwrench** [comment] 2019-06-12 10:07
Thanks for getting in touch @btomala - a stacktrace shouldn't be required when reporting errors to bugsnag. Bugsnag automatically captures any Throwables which propagate to the JVM's `UncaughtExceptionHandler`, and it's also possible to report an exception with an empty stacktrace manually, using the following API:

```
bugsnag.notify(exc); // report exception with empty stacktrace
```

We haven't verified that this behaviour works with Scala. Do you have an example of Scala code that throws an error which isn't reported to bugsnag, to allow us to track down the root cause of this issue?

**Comment by btomala** [comment] 2019-06-12 11:02
Hi, thanks for a response @fractalwrench 
We are using [BugsnagAppender](https://github.com/bugsnag/bugsnag-java/blob/master/bugsnag/src/main/java/com/bugsnag/BugsnagAppender.java) not directly call API. I check the source code and I think the problem is in [BugsnagAppender.java#L112](https://github.com/bugsnag/bugsnag-java/blob/master/bugsnag/src/main/java/com/bugsnag/BugsnagAppender.java#L112) and later.

I can prepare sample app for you but I think the code is self-explanatory. Removing a `throwable != null` should solve the issue.

**Comment by fractalwrench** [comment] 2019-06-12 11:06
I think a sample would be helpful in this case to clarify whether the log message contains a throwable with no stacktrace, or no stacktrace at all.

**Comment by btomala** [comment] 2019-06-12 11:41
Ok, I will write it for you.

**Comment by fractalwrench** [comment] 2019-06-18 08:30
Hi @btomala - just wanted to check whether this is still an issue for you?

**Comment by btomala** [comment] 2019-06-18 09:11
Hey, it's. I'm on Holiday now. I'll make sample when find some time or back.

**Comment by fractalwrench** [comment] 2019-07-04 10:52
@btomala hope you had a good holiday - was this still an issue you're encountering with bugsnag?

**Comment by fractalwrench** [comment] 2019-07-09 08:43
I am closing this issue as from the information given we're unable to confirm whether it's an issue with bugsnag or your integration. If you have further details to reproduce the issue please get in touch either by responding to this ticket or contacting support@bugsnag.com.

**Closed by fractalwrench** 2019-07-09 08:43 UTC

**Comment by btomala** [comment] 2019-07-11 17:27
Hi Jamie, sorry for being not responding. I had a busy week after a holiday. I deep dive into documentation and read again your comment above. And as I understand Bugsnag always require stack trace even if I send log entry directly via REST API. So my problem is that I want to have errors and warnings logged without stack trace in Bugsnag as well. This is impossible, am I correct?

**Comment by fractalwrench** [comment] 2019-07-12 08:03
`events[0].exceptions[0].stacktrace` is required by our Error Reporting API, but it's fine to supply an empty array if your errors have no stacktrace. bugsnag-java should do this automatically.

**Comment by btomala** [comment] 2019-07-12 10:30
Thanks for the response. So basically all bellow methods of logging should send an error to Bugsnag? 

```scala
val log = LoggerFactory.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME).asInstanceOf[ch.qos.logback.classic.Logger]
val appender = log.getAppender("BUGSNAG").asInstanceOf[BugsnagAppender]
val client = appender.getClient

client.notify(new RuntimeException("This works"))
log.error("This works as well", new RuntimeException("This works as well"))
log.error("This doesn't work")
```

Last one doesn't work for me.

**Comment by fractalwrench** [comment] 2019-07-12 10:34
@btomala there needs to be a `Throwable` for the `BugsnagAppender` to generate a report, so `log.error("This doesn't work")` would not send anything.

You could write a custom appender to wrap the message in an exception instead, or use `bugsnag.notify` directly.

**Comment by btomala** [comment] 2019-07-12 10:41
Ok, so this is what my concern was about. Yes, we already wrote own Appender. I thought that you should provide such Appender. Anyway, thanks for your help.
